services:
  db:
    image: postgres:16
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: ecotudo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jao
    ports:
      - 5432:5432
    networks:
      - gabriel-network

  rest-react-java-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo

      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/ecotudo
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: jao
      SPRING.JPA.DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect

      JWT_SECRET: 8f3c9a72d5e14b6c90a2f7e31d8c5b4a6e9f1234567890abcdef1234567890ab
      JWT_EXPIRATION: 86400000

    ports:
      - 8080:8080

    depends_on:
      - db

    networks:
      - gabriel-network

networks:
  gabriel-network:
    driver: bridge